name: ikuuu自动签到

# 定时触发：每天UTC时间0点（北京时间8点）运行
on:
  schedule:
    - cron: '0 0 * * *'  # 语法：分 时 日 月 周（UTC时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest  # 使用Ubuntu环境
    timeout-minutes: 10  # 超时时间10分钟

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 指定Python版本
          cache: 'pip'  # 缓存pip依赖

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行签到脚本
        run: python ikuuu_checkin.py
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}  # 引用GitHub Secrets中的账号密码

      - name: 输出执行时间
        run: echo "本次签到完成于: $(date '+%Y-%m-%d %H:%M:%S')"
