name: ikuuu自动签到（多账号+Telegram通知）

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 0点（北京时间8点）执行
  workflow_dispatch:  # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write  # 用于后续清理工作流

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: pip install requests

      - name: 运行签到脚本
        run: python ikuuu_checkin.py
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
