# 文件名：.github/workflows/auto-checkin.yml
name: ikuuu自动签到

# 触发条件：手动触发 + 定时触发
于:
  workflow_dispatch:  # 手动触发（这行决定是否显示Run workflow按钮）
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点（北京时间8点）运行

jobs:
  checkin:
    runs-on: ubuntu-latest  # 运行环境（固定写ubuntu-latest即可）
    timeout-minutes: 10  # 超时时间（防止卡住）

    steps:
      # 步骤1：拉取仓库代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 步骤2：安装Python
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Python版本（3.9/3.10/3.11都可）
          cache: 'pip'  # 缓存依赖，加速运行

      # 步骤3：安装requests库
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 步骤4：运行签到脚本（注意：脚本文件名要和你仓库中的一致！）
      - name: 执行签到
        run: python ikuuu_checkin.py  # 替换为你实际的Python脚本文件名
        env:
          IKUUU_ACCOUNTS: ${{ secrets.IKUUU_ACCOUNTS }}  # 引用Secrets中的账号

      # 步骤5：输出完成时间（可选，方便日志查看）
      - name: 记录完成时间
        run: echo "签到完成于：$(date '+%Y-%m-%d %H:%M:%S')"
